config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'contributors#index'
  resources :contributors, only: %i(index), param: :name do
    resources :commits, only: %i(index)
    collection do
      resources :search, only: %i(index), controller: 'contributors/search'
    end
  end
  
  get 'contributors/:period', to: 'contributors#index', as: 'contributors_in_period'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
# frozen_string_literal: true

class Commit < ApplicationRecord
  belongs_to :contributor

  def self.find_contributor(contributor_name)
    contributor = Contributor.find_by(name: contributor_name)
    contributor.avatar_url = '/assets/blank.svg' if contributor.avatar_url.nil?
    contributor
  end

  def self.search_comments(contributor)
    Commit.where(contributor_id: contributor.id).order(committed_on: :DESC)
  end
end

app/models/concerns/common_module.rb
# frozen_string_literal: true

module CommonModule
  extend ActiveSupport::Concern

  def self.replace_default_img(avatar)
    avatar = '/assets/blank.svg' if avatar.nil?
    avatar
  end
end

app/models/contributor.rb
# frozen_string_literal: true

class Contributor < ApplicationRecord
  include Rails.application.routes.url_helpers

  has_many :commits

  PERIODS =
    {
      'this-month' => 'This month',
      'this-year' => 'This year',
      'this-week' => 'This week',
      'today' => 'Today',
      'all-time' => 'All time'
    }.freeze

  class << self
    include Rails.application.routes.url_helpers
  end

  def self.rank(period)
    commit_ranks = []

    collect_contributors(commit_ranks, period)
    commit_count = commit_ranks.map { |hash| hash[:commits] }
    if commit_count
      commit_counts_sort_reverse = commit_count.sort.reverse
      commit_count.map! { |commit_number| commit_counts_sort_reverse.index(commit_number) + 1 }
      commit_ranks.zip(commit_count) { |contributor, rank| contributor[:rank] = rank }
    end
    commit_ranks.sort_by! { |hash| hash[:rank] }
  end

  def self.search_contributors(contributer_name)
    where('name like ?', "%#{ActiveRecord::Base.sanitize_sql_like(contributer_name)}%")
  end

  def self.change_for_display(contributers)
    contributers.map do |contributor|
      assign_contributor(contributor) unless contributor.nil?
    end
  end

  def self.collect_contributors(commit_ranks, period)
    Contributor.where.not(choice_period_commit_count(period)).each do |contributor|
      commit_ranks << {
        avatar_url: change_nil_avatar_to_default_img(contributor.avatar_url),
        rank: contributor.rank,
        path: contributor_commits_path(contributor_name: contributor.name),
        name: contributor.name,
        first_committed_on: contributor.first_committed_on,
        commits: choice_period_commit_count(period, contributor)
      }
    end
    commit_ranks
  end

  def self.choice_period_commit_count(period, contributor = nil)
    case period
    when 'today'
      contributor ? contributor.today_commits : { today_commits: 0 }
    when 'this-week'
      contributor ? contributor.this_week_commits : { this_week_commits: 0 }
    when 'this-month', nil
      contributor ? contributor.this_month_commits : { this_month_commits: 0 }
    when 'this-year'
      contributor ? contributor.this_year_commits : { this_year_commits: 0 }
    when 'all-time'
      contributor ? contributor.all_time_commits : { all_time_commits: 0 }
    end
  end

  def self.assign_contributor(contributor)
    {
      avatar_url: change_nil_avatar_to_default_img(contributor.avatar_url),
      name: contributor.name,
      path: Rails.application.routes.url_helpers.contributor_commits_path(contributor_name: contributor.name),
      commits: contributor.all_time_commits
    }
  end

  def self.change_nil_avatar_to_default_img(avatar)
    avatar = '/assets/blank.svg' if avatar.nil?
    avatar
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :all_contributors
end

app/controllers/commits_controller.rb
# frozen_string_literal: true

class CommitsController < ApplicationController
  def index
    @contributor = Commit.find_contributor(params[:contributor_name])
    @index = Commit.search_comments(@contributor)
  end
end

app/controllers/contributors/search_controller.rb
# frozen_string_literal: true

class Contributors::SearchController < ApplicationController
  def index
    contributers = Contributor.search_contributors(params[:name])
    @contributors = Contributor.change_for_display(contributers)
  end
end

app/controllers/contributors_controller.rb
# frozen_string_literal: true

class ContributorsController < ApplicationController
  def index
    @commit_ranks = Contributor.rank(params[:period])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def default_meta_tags
    {
      site: 'FjordBotCamp CONTRIBUTORS', title: "FjordBotCamp CONTRIBUTORS #{change_title}",
      reverse: true, charset: 'utf-8',
      description: "フィヨルドブートキャンプ アプリのリポジトリに対する#{change_description}commit数を集計し、ランキングを表示するサイトです。",
      keywords: 'FjordBotCamp,Contributors,Ruby', canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('favicon.ico') },
        {
          href: image_url('https://fjord-boot-camp-contributors-production.up.railway.app/assets/twitter-card-img.png'),\
          rel: 'apple-touch-icon', sizes: '1230x630', type: 'image/png'\
        }
      ],
      og: {
        site_name: :site, title: :title, description: :description,
        type: 'website', url: request.original_url,
        image: image_url('https://fjord-boot-camp-contributors-production.up.railway.app/assets/twitter-card-img.png'), local: 'ja-JP'
      },
      twitter: { card: 'summary_large_image', site: '@rosh_1228', image: image_url('twitter-card-img.png') }
    }
  end

  private

  def change_title
    params[:period].nil? ? 'This-month' : params[:period].capitalize
  end

  def change_description
    case params[:period]
    when 'this-month', nil
      '今月の'
    when 'this-year'
      '今年の'
    when 'this-week'
      '今週の'
    when 'today'
      '今日の'
    when 'all-time'
      '最初のcommitからの'
    end
  end
end

app/views/application/_global_nav.html.slim
nav.global-nav
  .container
    .global-nav__inner
      .global-nav__start
        .global-nav__tabs
          .tabs
            ul.tabs__items
              - Contributor::PERIODS.each do |key, period|
                li.tabs__item
                  - path = contributors_in_period_path(key)
                  - if params[:period]
                    = link_to period, path, class: "tabs__item-link #{params[:period] == key ? 'is-active' : ''}"
                  - elsif params[:controller] == 'contributors'
                    = link_to period, path, class: "tabs__item-link #{'this-month' == key ? 'is-active' : ''}"
                  - else
                    = link_to period, path, class: 'tabs__item-link'
      .global-nav__end
        .global-nav__search
          = react_component('Search')

app/views/application/_header.html.slim
header.header
  .container
    .header__inner
      .header__start
        .header__logo
          = link_to contributors_path, class: 'header__logo-link' do
            = image_tag('pijord.svg', alt: 'フィヨルドブートキャンプのマーク', class: 'header__logo-image')
            .header__logo-type
              | FBC Contributors
        = react_component('Description')
      .header__end
        input#drawer-input.is-hidden-checkbox(type='checkbox')
        label.header__drawer-open(for='drawer-input')
          span.header__drawer-open-icon
        nav.header__nav
          .header__nav-items
            .header__nav-item.is-about
              = react_component('Description')
            .header__nav-item
              = link_to 'https://bootcamp.fjord.jp/', target: '_blank', rel: 'noopener', class: 'header__nav-item-link' do
                | FjordBootCamp
            .header__nav-item
              = link_to 'https://github.com/fjordllc/bootcamp', target: '_blank', rel: 'noopener', class: 'header__nav-item-link' do
                | Contribution on Github
          label.header__nav-overlay(for='drawer-input')

app/views/commits/index.html.slim
header.main__header
  .container
    .main__header-inner
      .contributor
        .contributor__avatar
          = image_tag @contributor.avatar_url, class: 'contributor__avatar-image'
          .contributor__rank
            = "##{@contributor.rank}"
        h1.contributor__name
          = @contributor.name
.commits
  .container
    = react_component('CommitList', { commits: @index })

app/views/contributors/index.html.slim
header.main__header
  .container
    .main__header-inner
      h1.main__title
        - if params[:period].nil?
          = 'Contributors - This month'
        - else
          = "Contributors - #{params[:period].capitalize.tr('-', ' ')}"
.main__body
  - if @commit_ranks.blank?
    .main-empty
      .container
        .main-empty__inner
          i.far.fa-sad-tear
          p.main-empty__message
            | Today has no commit.
  - else
    = react_component('ContributorList', { ranks: @commit_ranks })

app/views/contributors/search/index.html.slim
header.main__header
  .container
    .main__header-inner
      h1.main__title
        | Search for '#{params[:name]}'
.main__body
  - if @contributors.blank?
    .main-empty
      .container
        .main-empty__inner
          i.far.fa-sad-tear
          p.main-empty__message
            | No contributor found.
  - else
    = react_component('SearchResult', { contributors: @contributors })

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    title
      | FjordBootCampContributors
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    link rel='preconnect' href='https://fonts.googleapis.com'
    link rel='preconnect' href='https://fonts.gstatic.com'
    link href='https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap' rel='stylesheet'
    link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css' rel='stylesheet'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    = favicon_link_tag 'fav180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png'
    = favicon_link_tag 'fav192x192.png', rel: 'android-touch-icon', sizes: '192x192', type: 'image/png'
  body
    a(name='top')
    = render 'header'
    = render 'global_nav'
    main.main
      = yield
    a(name='bottom')
    nav.scroll-nav
      ul.scroll-nav__items
        li.scroll-nav__item
          = link_to '#top', class: 'scroll-nav__item-link' do
            i.fas.fa-angle-up
        li.scroll-nav__item
          = link_to '#bottom', class: 'scroll-nav__item-link' do
            i.fas.fa-angle-down